version: "3"
services:
    rabbitmq:
        image: rabbitmq:3.8.11-management
        container_name: rabbitmq
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:15672:15672"
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 2G
                reservations:
                    cpus: "1"
                    memory: 512M
    master:
      build: dockerfiles/Master
      tty: true
      volumes:
          - ./php/client:/home/ubuntu/client
          - ./php/analysis:/home/ubuntu/analysis
          - ./php/debloating_templates:/home/ubuntu/debloating_templates
      deploy:
        replicas: 5
        resources:
          limits:
            cpus: "1"
            memory: 512M
          reservations:
            cpus: "0.25"
            memory: 128M
      restart: always
    run:
      build: dockerfiles/Run
      tty: true
      volumes:
        - ./php/client:/home/ubuntu/client
        - ./php/analysis:/home/ubuntu/analysis
        - ./php/debloating_templates:/home/ubuntu/debloating_templates
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "1"
            memory: 128M
          reservations:
            cpus: "0.25"
            memory: 128M
    worker:
      build: dockerfiles/PHPWorker
      tty: true
      volumes:
          - ./php/client:/home/ubuntu/client
          - ./php/debloating_templates:/home/ubuntu/debloating_templates
      deploy:
        mode: replicated
        replicas: 20
        resources:
          limits:
            cpus: "1"
            memory: 1G
          reservations:
            cpus: "0.5"
            memory: 256M
      restart: always
    debug_worker:
        build: dockerfiles/PHPWorkerNoMQ
        tty: true
        volumes:
            - ./php/client:/home/ubuntu/client
            - ./php/debloating_templates:/home/ubuntu/debloating_templates
    apache:
        build: dockerfiles/Apache
        container_name: apache
        volumes:
            - ./php/debloating_templates/app:/var/www/html
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: grafana
            MYSQL_USER: cc_user
            MYSQL_PASSWORD: cc_password
        ports:
            - "127.0.0.1:6033:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./dockerfiles/db:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "127.0.0.1:8080:80"
    grafana:
        image: grafana/grafana:latest
        ports:
            - "127.0.0.1:3000:3000"
        environment: 
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: admin
            GF_DATABASE_TYPE: mysql
            GF_DATABASE_HOST: db:3306
            GF_DATABASE_NAME: grafana
            GF_DATABASE_USER: cc_user
            GF_DATABASE_PASSWORD: cc_password
        volumes:
            - grafana-storage:/var/lib/grafana
        restart: always
    redis:
      image: redis:bullseye
volumes:
    dbdata:
    grafana-storage:
